parser: babel-eslint

# So parent files don't get applied
root: true

env:
  es6: true
  browser: true
  node: true

plugins:
  - react

rules:
  brace-style: [2, 1tbs, {allowSingleLine: false}]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  eqeqeq: [2, smart]
  eol-last: 2
  indent: [2, 2, {SwitchCase: 0}]
  jsx-quotes: [2, prefer-double]
  key-spacing: 2
  keyword-spacing: 2
  max-len: 0 # TODO
  no-unused-expressions: 2
  no-unused-vars: 2
  no-shadow: 2
  no-spaced-func: 2
  no-multi-spaces: 2
  no-undef: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-cond-assign: 2
  no-extra-semi: 2
  no-extra-boolean-cast: 2
  no-trailing-spaces: 2
  no-unreachable: 2
  no-var: 2
  object-curly-spacing: [2, never]
  prefer-arrow-callback: 2
  prefer-const: 2
  quotes: [2, single, avoid-escape]
  semi-spacing: 2
  semi: [2, always]
  space-before-blocks: [2, always]
  space-before-function-paren: [2, always]
  space-infix-ops: 2
  space-unary-ops: [2, { words: true, nonwords: false }]

  # React
  react/display-name: 2
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: 2
  react/jsx-max-props-per-line: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-no-undef: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/jsx-wrap-multilines: 2
  react/no-danger: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-multi-comp: 2
  react/no-unknown-property: 2
  react/prop-types: 0 # TODO
  react/react-in-jsx-scope: 2
  react/require-extension: 0 # TODO
  react/sort-comp: 2
  react/sort-prop-types: 2
